config/routes.rb
Rails.application.routes.draw do
  resources :cars do as_routes end
  resources :employees do as_routes end
  resources :companies do as_routes end
  resources :empresas

  devise_for :users, controllers: { sessions: "users/sessions" }
  resources :users

  root 'welcome#index'

end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  before_action :set_empresa, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!

  # GET /empresas
  # GET /empresas.json
  def index
    @empresas = Empresa.all
  end

  # GET /empresas/1
  # GET /empresas/1.json
  def show
  end

  # GET /empresas/new
  def new
    @empresa = Empresa.new
  end

  # GET /empresas/1/edit
  def edit
  end

  # POST /empresas
  # POST /empresas.json
  def create
    @empresa = Empresa.new(empresa_params)

    respond_to do |format|
      if @empresa.save
        format.html { redirect_to @empresa, notice: 'Empresa was successfully created.' }
        format.json { render :show, status: :created, location: @empresa }
      else
        format.html { render :new }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empresas/1
  # PATCH/PUT /empresas/1.json
  def update
    respond_to do |format|
      if @empresa.update(empresa_params)
        format.html { redirect_to @empresa, notice: 'Empresa was successfully updated.' }
        format.json { render :show, status: :ok, location: @empresa }
      else
        format.html { render :edit }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empresas/1
  # DELETE /empresas/1.json
  def destroy
    @empresa.destroy
    respond_to do |format|
      format.html { redirect_to empresas_url, notice: 'Empresa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empresa
      @empresa = Empresa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empresa_params
      params.require(:empresa).permit(:razon_social, :rut, :representante, :giro, :doreccion)
    end
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/views/empresas/_form.html.erb
<%= simple_form_for(@empresa) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :razon_social %>
    <%= f.input :rut %>
    <%= f.input :representante %>
    <%= f.input :giro %>
    <%= f.input :doreccion %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/empresas/edit.html.erb
<h1>Editing Empresa</h1>

<%= render 'form' %>

<%= link_to 'Show', @empresa %> |
<%= link_to 'Back', empresas_path %>

app/views/empresas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Empresas</h1>

<table>
  <thead>
    <tr>
      <th>Razon social</th>
      <th>Rut</th>
      <th>Representante</th>
      <th>Giro</th>
      <th>Doreccion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @empresas.each do |empresa| %>
      <tr>
        <td><%= empresa.razon_social %></td>
        <td><%= empresa.rut %></td>
        <td><%= empresa.representante %></td>
        <td><%= empresa.giro %></td>
        <td><%= empresa.doreccion %></td>
        <td><%= link_to 'Show', empresa %></td>
        <td><%= link_to 'Edit', edit_empresa_path(empresa) %></td>
        <td><%= link_to 'Destroy', empresa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Empresa', new_empresa_path %>

app/views/empresas/new.html.erb
<h1>New Empresa</h1>

<%= render 'form' %>

<%= link_to 'Back', empresas_path %>

app/views/empresas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Razon social:</strong>
  <%= @empresa.razon_social %>
</p>

<p>
  <strong>Rut:</strong>
  <%= @empresa.rut %>
</p>

<p>
  <strong>Representante:</strong>
  <%= @empresa.representante %>
</p>

<p>
  <strong>Giro:</strong>
  <%= @empresa.giro %>
</p>

<p>
  <strong>Doreccion:</strong>
  <%= @empresa.doreccion %>
</p>

<%= link_to 'Edit', edit_empresa_path(@empresa) %> |
<%= link_to 'Back', empresas_path %>